backend:
  image: "asia-south1-docker.pkg.dev/project-8544d2b1-f78e-4448-bfc/pencraft/java-store"
  replicaCount: 1
frontend:
  image: "asia-south1-docker.pkg.dev/project-8544d2b1-f78e-4448-bfc/pencraft/frontend"
  replicaCount: 1
